version: "3.8"

services:
  flexlog-postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./flexlog-init.sql:/docker-entrypoint-initdb.d/init.sql
      - flexlog-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: flexlog
    ports:
      - "5433:5432"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  flexlog-data:
